### ISSUE TITLE
Learning HTML5, Bootstrap

### ISSUE THREAD

**Issue by lessuknow** [faroos3/pellio#3]
As I am new to web development as a whole, I will spend this time learning Bootstrap and HTML5 in order to make the frontend look as appealing as possible. As this issue is more of an overarching one, this issue may take a while to be resolved.

**Comment by calerc1** [comment]
The semester has come to an end and I can safely say that the most valuable thing that I have gotten out of this project is having learned HTML, CSS and Bootstrap. They are the things that I'm the most comfortable using in our project, and I have even used them in other projects like that I worked on this semester.
